- name: Create Jenkins Jobs
  hosts: localhost
  roles:
    - role: jenkins-jobs
      vars:
        jobs:
          - { jobName: "roboshop-frontend", repoName: "raghudevopsb79/roboshop-frontend", triggerToken: "roboshop-frontend"}
          - { jobName: "roboshop-catalogue", repoName: "raghudevopsb79/roboshop-catalogue", triggerToken: "roboshop-catalogue"}
          - { jobName: "roboshop-cart", repoName: "raghudevopsb79/roboshop-cart", triggerToken: "roboshop-cart"}
          - { jobName: "roboshop-user", repoName: "raghudevopsb79/roboshop-user", triggerToken: "roboshop-user"}
          - { jobName: "roboshop-shipping", repoName: "raghudevopsb79/roboshop-shipping", triggerToken: "roboshop-shipping"}
          - { jobName: "roboshop-payment", repoName: "raghudevopsb79/roboshop-payment", triggerToken: "roboshop-payment"}
          - { jobName: "roboshop-dispatch", repoName: "raghudevopsb79/roboshop-dispatch", triggerToken: "roboshop-dispatch"}

