- name: Create template file
  ansible.builtin.template:
    src: multi-branch.xml
    dest: /tmp/multi-branch.xml

- name: Create Jenkins job
  community.general.jenkins_job:
    config: "{{ lookup('file', '/tmp/multi-branch.xml') }}"
    name: "{{ item.jobName }}"
    password: admin123
    url: http://jenkins-internal.rdevopsb79.online:8080
    user: admin
