- name: Create template file
  ansible.builtin.template:
    src: multi-branch.xml
    dest: /tmp/multi-branch.xml

- name: Create Jenkins job
  community.general.jenkins_job:
    config: "{{ lookup('file', '/tmp/multi-branch.xml') }}"
    name: "{{ item.jobName }}"
    password: "{{ secrets.password }}"
    url: http://jenkins-internal.rdevopsb79.online:8080
    user: "{{ secrets.user }}"

- name: Create WebHook
  community.general.github_webhook:
    repository: "{{ item.repoName }}"
    url: http://jenkins.rdevopsb79.online:8080/multibranch-webhook-trigger/invoke?token={{ item.triggerToken }}
    events:
      - push
    user: "{{ secrets.github_user }}"
    token: "{{ secrets.github_token }}"


